blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/axar-ai/axar/discussions
    about: Please ask your questions in our discussions forum.
  - name: Contribute
    url: https://github.com/axar-ai/axar/blob/main/CONTRIBUTING.md
    about: Learn more about how to contribute to axar.
