name: Smokeshow

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

permissions:
  actions: read
  contents: read
  statuses: write

jobs:
  smokeshow:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Download coverage artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: CI # Ensure the correct workflow name or ID
          name: coverage-final-json
          commit: ${{ github.event.workflow_run.head_sha }}

      - name: List downloaded artifacts
        run: ls -R coverage-final.json || echo "No artifacts found"

      - name: Upload coverage to Smokeshow
        run: |
          npx smokeshow upload coverage-final.json
        env:
          SMOKESHOW_GITHUB_STATUS_DESCRIPTION: Coverage {coverage-percentage}
          SMOKESHOW_GITHUB_COVERAGE_THRESHOLD: 95
          SMOKESHOW_GITHUB_CONTEXT: coverage
          SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMOKESHOW_AUTH_KEY: ${{ secrets.SMOKESHOW_AUTH_KEY }}
