name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write # For fetching code and pushing tags/releases
      id-token: write # For OIDC tokenless publishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '20.12.2'
          registry-url: 'https://registry.npmjs.org/'

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Release with Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npx semantic-release

      - name: Publish to JSR
        run: npx jsr publish
